image: golang:1.12.9

lint:
  before_script:
    - shopt -s dotglob
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/ | grep -v /build/) # All the .go files, excluding vendor/
    - make bin/golangci-lint
  script:
    #    - CGO_ENABLED=0 bin/golangci-lint --color never run -j 1 --build-tags static,netgo,osusergo --config .golangci.yml --out-format line-number
    - make linter

build:
  script:
    - make all
    - git clone https://gitlab.com/aquachain/bootstraps ../bootstraps
    - ./bin/aquachain import ../bootstraps/latest.dat

test:
  script:
    - make test

