run:
  tests: false
issues:
  exclude-dirs:
  # TODO remove these exclusions
    - crypto/sha3$
    - vendor$
    - build$
    - testing$
    - ^p2p/simulations$
    - ^p2p/simulations
    - ^p2p/testing
output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  gofmt:
    simplify: true
  goimports:
    local-prefixes: gitlab.com/aquachain/aquachain
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
    ignore-words:
      - aquachain
      - Aquachain
  lll:
    line-length: 120
    tab-width: 1
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
linters:
  enable:
    - gosec
    # - megacheck
    - govet
    - deadcode
  enable-all: false
  # disable:
    # - maligned
    # - prealloc
  disable-all: true
  presets:
    - bugs
  # fast: true


