language: go
go_import_path: gitlab.com/aquachain/aquachain
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: "1.11"
      env:
        - test
      script:
        - sudo modprobe fuse
        - sudo chmod ugo+rw /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test -coverage
    - os: linux
      dist: alpine
      sudo: required
      go: "1.11"
      env:
        - build
      script:
        - sudo modprobe fuse
        - sudo chmod ugo+rw /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install -musl
        - git clone https://gitlab.com/aquachain/bootstraps.git /tmp/bootstraps
        - go run build/ci.go import-test /tmp/bootstraps/latest.dat

    - os: linux
      dist: trusty
      go: "1.11"
      env:
        - lint
      git:
        submodules: false # avoid cloning aquachain/tests
      script:
        - go run build/ci.go lint
