name: Autobuild+Upload
on: # any push any branch any repo
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build aquachain
        run: make
      - name: show system info
        run: env || true; uname -a || true; test ! -e /etc/os-release || cat /etc/os-release;
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: aquachain-${{ github.sha }}-${{github.ref_name || github.run_id }}-${{ matrix.operating-system}}
          path: bin/*
