name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ci/${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Build/Run Test (Ubuntu/Windows)
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-24.04, ubuntu-22.04, windows-2025, windows-2022]
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v3
      - name: Build aquachain
        run: make
      - name: show system info
        run: env || true; uname -a || true; test ! -e /etc/os-release || cat /etc/os-release;
      - name: Test (short)
        run: bash testing/test-short-only.bash
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aquachain-${{ github.sha }}-${{github.ref_name || github.run_id }}-${{ matrix.operating-system}}
          path: bin/*
          retention-days: 90