name: Grep check

on: [push, pull_request]

jobs:
  badcodegrep:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-tags: true
      - name: grepping for bad funcs
        run: |
          .github/grepcheck "os.LookupEnv" "sense.LookupEnv" 1;
          .github/grepcheck "os.Getenv" "sense.Getenv" 1;
          .github/grepcheck "os.Exit" "log.GracefulShutdown" 19 warn;
          .github/grepcheck "log.Fatal" "log.GracefulShutdown" 0;
          .github/grepcheck "log.Fataln" "log.GracefulShutdown" 1;
          .github/grepcheck "log.Fatalf" "log.GracefulShutdown" 0;

