name: Prerelease Build
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ci/${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Build Pre-release
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-24.04, windows-2025]
        # operating-system: [ubuntu-24.04, ubuntu-22.04, windows-2025, windows-2022]
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v4
      - name: show system info
        run: env || true; uname -a || true; test ! -e /etc/os-release || cat /etc/os-release; echo ${{ github.ref_name }} - ${{ github.ref }}
      - name: Build aquachain
        run: make clean release release=1 codename=nightly
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aquachain-${{ github.ref_name || 'v0.0.0-auto' }}-${{ github.sha }}-${{ github.run_id }}-${{ matrix.operating-system}}
          path: release/*
          retention-days: 90
      # - name: Run tests (short only)
      #   run: make test