name: Prerelease Build
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ci/${{ github.ref }}/release
  cancel-in-progress: true

jobs:
  run:
    name: Build Pre-release
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        # operating-system: [ubuntu-24.04, ubuntu-22.04, windows-2025, windows-2022]
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-tags: true
      - name: show system info
        run: env || true; uname -a || true; test ! -e /etc/os-release || cat /etc/os-release; echo ${{ github.ref_name }} - ${{ github.ref }}
      - name: Build aquachain
        run: time make clean release release=1 codename=nightly
      - name: Upload artifacts
        uses: aerth/upload-artifacts@v4.6.4-aerth
        with:
          path: release/
